Controllers/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GiraffeBooking.Models;
using GiraffeBooking.Models.ViewModels;
using GiraffeBooking.Data;


namespace GiraffeBooking.Controllers
{
    public class BookingsController : Controller
    {
        public BookingsController()
        {

        }

        // GET: Bookings
        public IActionResult Index()
        {
            var bookings = GiraffeBookingContext.Bookings;

            return View(bookings);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            var createBookingViewModel = new CreateBookingViewModel() { Giraffes = GiraffeBookingContext.Giraffes };
            return View(createBookingViewModel);
        }


        // POST: Bookings/Create
        [HttpPost]
        // från vyn till metoden i controllern
        public IActionResult Create(Booking booking)
        {
            var giraffe = GiraffeBookingContext.Giraffes.FirstOrDefault(r => r.Id == booking.GiraffeId);

            if (giraffe == null)
            {
                return RedirectToAction(nameof(Create));
            }
            
            if (ModelState.IsValid)
            {
                booking.Id = Guid.NewGuid();
                booking.GiraffeName = giraffe.Name;
                GiraffeBookingContext.Bookings.Add(booking);
                return RedirectToAction("Index");
            }

            return View(giraffe);
        }

        // GET: Bookings/Edit/5
        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = GiraffeBookingContext.Bookings.FirstOrDefault(b => b.Id == id)
                ;

            if (booking == null) 
            {
                return NotFound();
            }

            var editBookingViewModel = new EditBookingViewModel() { Booking = booking, Giraffes = GiraffeBookingContext.Giraffes };
            return View(editBookingViewModel);
        }

        // POST: Bookings/Edit/5 
        [HttpPost]
        public IActionResult Edit(Booking booking)
        {
            booking.GiraffeName = GiraffeBookingContext.Giraffes.FirstOrDefault(r => r.Id == booking.GiraffeId).Name;

            var bookingIndex= GiraffeBookingContext.Bookings.FindIndex(m => m.Id == booking.Id);



            if (bookingIndex == -1)
            {
                return NotFound();
            }

            GiraffeBookingContext.Bookings[bookingIndex] = booking;

            return RedirectToAction(nameof(Index));
        }

        // GET: Booking/Delete/5
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giraffe = GiraffeBookingContext.Bookings.FirstOrDefault(r => r.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);

        }

        // POST: Bookings/Delete/5
        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var giraffe = GiraffeBookingContext.Bookings.FirstOrDefault(r => r.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            GiraffeBookingContext.Bookings.Remove(giraffe);

            return RedirectToAction("Index");
        }

    }
}

Controllers/GiraffesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GiraffeBooking.Models;
using GiraffeBooking.Data;

namespace GiraffeBooking.Controllers
{
    public class GiraffesController : Controller
    {
        public GiraffesController()
        {
            
        }

        // GET: Giraffes
        public IActionResult Index()
        {
            var giraffes = GiraffeBookingContext.Giraffes;

            return View(giraffes);
        }

        // GET: Giraffes/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Giraffes/Create
        [HttpPost]
        // från vyn till metoden i controllern.
        public IActionResult Create(Giraffe giraffe)
        {
            if (ModelState.IsValid)
            {
                giraffe.Id = Guid.NewGuid();
                GiraffeBookingContext.Giraffes.Add(giraffe);
                return RedirectToAction("Index");
            }

            return View(giraffe);
        }

        // GET: Giraffes/Edit/5
        public IActionResult Edit(Guid id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var giraffe = GiraffeBookingContext.Giraffes.FirstOrDefault(r => r.Id == id);

            if(giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);

        }

        // POST: Giraffes/Edit/5
        [HttpPost]
        public IActionResult Edit(Giraffe giraffe) 
        {
            if (ModelState.IsValid)
            {
                var giraffeIndex = GiraffeBookingContext.Giraffes.FindIndex(m => m.Id == giraffe.Id);

                if (giraffeIndex == -1)
                {
                    return NotFound();
                }

                GiraffeBookingContext.Giraffes[giraffeIndex] = giraffe;

                return RedirectToAction(nameof(Index));
            }

            return View(giraffe);

        }

        // GET: Giraffes/Delete/5
        public IActionResult Delete(Guid id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var giraffe = GiraffeBookingContext.Giraffes.FirstOrDefault(r => r.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            return View(giraffe);
        }


        // POST: Giraffes/Delete/5
        [HttpPost]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var giraffe = GiraffeBookingContext.Giraffes.FirstOrDefault(r => r.Id == id);

            if (giraffe == null)
            {
                return NotFound();
            }

            GiraffeBookingContext.Giraffes.Remove(giraffe);

            return RedirectToAction("Index");

        }


    }


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Giraffe Booker App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/giraffe.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Giraffe Booker App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Giraffes" asp-action="Index">All giraffes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">All bookings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Giraffe Booker App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>